[2025-02-05T02:56:42.557+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-05T02:56:42.572+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nasa_dag.extract_data manual__2025-02-05T02:56:38.155447+00:00 [queued]>
[2025-02-05T02:56:42.580+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nasa_dag.extract_data manual__2025-02-05T02:56:38.155447+00:00 [queued]>
[2025-02-05T02:56:42.581+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-02-05T02:56:42.592+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): extract_data> on 2025-02-05 02:56:38.155447+00:00
[2025-02-05T02:56:42.596+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=88) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-05T02:56:42.598+0000] {standard_task_runner.py:72} INFO - Started process 89 to run task
[2025-02-05T02:56:42.598+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'nasa_dag', 'extract_data', 'manual__2025-02-05T02:56:38.155447+00:00', '--job-id', '305', '--raw', '--subdir', 'DAGS_FOLDER/nasa_dag.py', '--cfg-path', '/tmp/tmpv12qvlbv']
[2025-02-05T02:56:42.599+0000] {standard_task_runner.py:105} INFO - Job 305: Subtask extract_data
[2025-02-05T02:56:42.637+0000] {task_command.py:467} INFO - Running <TaskInstance: nasa_dag.extract_data manual__2025-02-05T02:56:38.155447+00:00 [running]> on host fbf16bed15ba
[2025-02-05T02:56:42.699+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='milo0@gmail.com' AIRFLOW_CTX_DAG_OWNER='camilo' AIRFLOW_CTX_DAG_ID='nasa_dag' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-05T02:56:38.155447+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-05T02:56:38.155447+00:00'
[2025-02-05T02:56:42.700+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-05T02:56:42.711+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-05T02:56:42.712+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/tmp/extract_api_nasa.py']
[2025-02-05T02:56:42.719+0000] {subprocess.py:86} INFO - Output:
[2025-02-05T02:56:46.901+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.12/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.telegram.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2025-02-05T02:56:46.902+0000] {subprocess.py:93} INFO -   warnings.warn(
[2025-02-05T02:56:47.564+0000] {subprocess.py:93} INFO - {'copyright': '\nJulene Eiguren\n', 'date': '2025-02-04', 'explanation': "Yes, but can your rainbow do this? Late in the day, the Sun set as usual toward the west. However, on this day, the more interesting display was 180 degrees around -- toward the east. There, not only was a rainbow visible, but an impressive display of anticrepuscular rays from the rainbow's center. In the featured image from Lekeitio in northern Spain, the Sun is behind the camera. The rainbow resulted from sunlight reflecting back from falling rain. Anticrepuscular rays result from sunlight, blocked by some clouds, going all the way around the sky, overhead, and appearing to converge on the opposite horizon -- an optical illusion.  Rainbows by themselves can be exciting to see, and anticrepuscular rays a rare treat, but capturing them both together is even more unusual -- and can look both serene and surreal.   Jigsaw Challenge: Astronomy Puzzle of the Day", 'hdurl': 'https://apod.nasa.gov/apod/image/2502/RainbowFan_Eiguren_3228.jpg', 'media_type': 'image', 'service_version': 'v1', 'title': 'Anticrepuscular Rays: A Rainbow Fan over Spain', 'url': 'https://apod.nasa.gov/apod/image/2502/RainbowFan_Eiguren_1080.jpg'}
[2025-02-05T02:56:47.566+0000] {subprocess.py:93} INFO - Nuevo objeto agregado al archivo /opt/***/tmp/data.json
[2025-02-05T02:56:47.602+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-02-05T02:56:47.627+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-05T02:56:47.628+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=nasa_dag, task_id=extract_data, run_id=manual__2025-02-05T02:56:38.155447+00:00, execution_date=20250205T025638, start_date=20250205T025642, end_date=20250205T025647
[2025-02-05T02:56:47.659+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-05T02:56:47.676+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-05T02:56:47.678+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
