[2025-01-21T00:47:59.524+0000] {processor.py:186} INFO - Started process (PID=50) to work on /opt/airflow/dags/nasa_dag.py
[2025-01-21T00:47:59.525+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/nasa_dag.py for tasks to queue
[2025-01-21T00:47:59.527+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:47:59.526+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/nasa_dag.py
[2025-01-21T00:47:59.557+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:47:59.550+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/nasa_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nasa_dag.py", line 7, in <module>
    from airflow.providers.mongo.hooks.mongo import MongoHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2025-01-21T00:47:59.559+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/nasa_dag.py
[2025-01-21T00:47:59.578+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/nasa_dag.py took 0.060 seconds
[2025-01-21T00:48:29.926+0000] {processor.py:186} INFO - Started process (PID=57) to work on /opt/airflow/dags/nasa_dag.py
[2025-01-21T00:48:29.927+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/nasa_dag.py for tasks to queue
[2025-01-21T00:48:29.929+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:48:29.928+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/nasa_dag.py
[2025-01-21T00:48:29.944+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:48:29.941+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/nasa_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nasa_dag.py", line 7, in <module>
    from airflow.providers.mongo.hooks.mongo import MongoHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2025-01-21T00:48:29.944+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/nasa_dag.py
[2025-01-21T00:48:29.959+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/nasa_dag.py took 0.036 seconds
[2025-01-21T00:49:00.316+0000] {processor.py:186} INFO - Started process (PID=64) to work on /opt/airflow/dags/nasa_dag.py
[2025-01-21T00:49:00.316+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/nasa_dag.py for tasks to queue
[2025-01-21T00:49:00.318+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:49:00.318+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/nasa_dag.py
[2025-01-21T00:49:00.336+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:49:00.332+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/nasa_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nasa_dag.py", line 7, in <module>
    from airflow.providers.mongo.hooks.mongo import MongoHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2025-01-21T00:49:00.337+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/nasa_dag.py
[2025-01-21T00:49:00.355+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/nasa_dag.py took 0.042 seconds
[2025-01-21T00:49:30.709+0000] {processor.py:186} INFO - Started process (PID=71) to work on /opt/airflow/dags/nasa_dag.py
[2025-01-21T00:49:30.710+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/nasa_dag.py for tasks to queue
[2025-01-21T00:49:30.711+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:49:30.711+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/nasa_dag.py
[2025-01-21T00:49:30.732+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:49:30.727+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/nasa_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nasa_dag.py", line 7, in <module>
    from airflow.providers.mongo.hooks.mongo import MongoHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2025-01-21T00:49:30.734+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/nasa_dag.py
[2025-01-21T00:49:30.753+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/nasa_dag.py took 0.048 seconds
[2025-01-21T00:50:01.059+0000] {processor.py:186} INFO - Started process (PID=78) to work on /opt/airflow/dags/nasa_dag.py
[2025-01-21T00:50:01.060+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/nasa_dag.py for tasks to queue
[2025-01-21T00:50:01.061+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:50:01.061+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/nasa_dag.py
[2025-01-21T00:50:01.079+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:50:01.075+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/nasa_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nasa_dag.py", line 7, in <module>
    from airflow.providers.mongo.hooks.mongo import MongoHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2025-01-21T00:50:01.080+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/nasa_dag.py
[2025-01-21T00:50:01.100+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/nasa_dag.py took 0.048 seconds
[2025-01-21T00:59:21.443+0000] {processor.py:186} INFO - Started process (PID=50) to work on /opt/airflow/dags/nasa_dag.py
[2025-01-21T00:59:21.444+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/nasa_dag.py for tasks to queue
[2025-01-21T00:59:21.446+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:59:21.446+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/nasa_dag.py
[2025-01-21T00:59:21.462+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:59:21.459+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/nasa_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nasa_dag.py", line 7, in <module>
    from airflow.providers.mongo.hooks.mongo import MongoHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2025-01-21T00:59:21.463+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/nasa_dag.py
[2025-01-21T00:59:21.478+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/nasa_dag.py took 0.040 seconds
[2025-01-21T00:59:51.830+0000] {processor.py:186} INFO - Started process (PID=57) to work on /opt/airflow/dags/nasa_dag.py
[2025-01-21T00:59:51.831+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/nasa_dag.py for tasks to queue
[2025-01-21T00:59:51.832+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:59:51.832+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/nasa_dag.py
[2025-01-21T00:59:51.845+0000] {logging_mixin.py:190} INFO - [2025-01-21T00:59:51.842+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/nasa_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nasa_dag.py", line 7, in <module>
    from airflow.providers.mongo.hooks.mongo import MongoHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2025-01-21T00:59:51.846+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/nasa_dag.py
[2025-01-21T00:59:51.862+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/nasa_dag.py took 0.035 seconds
[2025-01-21T01:00:22.199+0000] {processor.py:186} INFO - Started process (PID=64) to work on /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:00:22.200+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/nasa_dag.py for tasks to queue
[2025-01-21T01:00:22.202+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:00:22.201+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:00:22.217+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:00:22.214+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/nasa_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nasa_dag.py", line 7, in <module>
    from airflow.providers.mongo.hooks.mongo import MongoHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2025-01-21T01:00:22.218+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:00:22.232+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/nasa_dag.py took 0.037 seconds
[2025-01-21T01:00:52.472+0000] {processor.py:186} INFO - Started process (PID=77) to work on /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:00:52.473+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/nasa_dag.py for tasks to queue
[2025-01-21T01:00:52.476+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:00:52.475+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:00:52.489+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:00:52.485+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/nasa_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nasa_dag.py", line 7, in <module>
    from airflow.providers.mongo.hooks.mongo import MongoHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2025-01-21T01:00:52.491+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:00:52.508+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/nasa_dag.py took 0.041 seconds
[2025-01-21T01:01:22.846+0000] {processor.py:186} INFO - Started process (PID=84) to work on /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:01:22.847+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/nasa_dag.py for tasks to queue
[2025-01-21T01:01:22.849+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:01:22.849+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:01:22.861+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:01:22.859+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/nasa_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nasa_dag.py", line 7, in <module>
    from airflow.providers.mongo.hooks.mongo import MongoHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2025-01-21T01:01:22.862+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:01:22.877+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/nasa_dag.py took 0.036 seconds
[2025-01-21T01:02:40.676+0000] {processor.py:186} INFO - Started process (PID=50) to work on /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:02:40.678+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/nasa_dag.py for tasks to queue
[2025-01-21T01:02:40.680+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:02:40.679+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:02:40.696+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:02:40.691+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/nasa_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nasa_dag.py", line 7, in <module>
    from airflow.providers.mongo.hooks.mongo import MongoHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2025-01-21T01:02:40.697+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:02:40.716+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/nasa_dag.py took 0.047 seconds
[2025-01-21T01:03:11.092+0000] {processor.py:186} INFO - Started process (PID=57) to work on /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:03:11.092+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/nasa_dag.py for tasks to queue
[2025-01-21T01:03:11.094+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:03:11.093+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:03:11.102+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:03:11.100+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/nasa_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nasa_dag.py", line 7, in <module>
    from airflow.providers.mongo.hooks.mongo import MongoHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2025-01-21T01:03:11.104+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:03:11.119+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/nasa_dag.py took 0.031 seconds
[2025-01-21T01:03:41.491+0000] {processor.py:186} INFO - Started process (PID=64) to work on /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:03:41.492+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/nasa_dag.py for tasks to queue
[2025-01-21T01:03:41.494+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:03:41.494+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:03:41.509+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:03:41.507+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/nasa_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nasa_dag.py", line 7, in <module>
    from airflow.providers.mongo.hooks.mongo import MongoHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2025-01-21T01:03:41.510+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:03:41.527+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/nasa_dag.py took 0.040 seconds
[2025-01-21T01:04:11.898+0000] {processor.py:186} INFO - Started process (PID=71) to work on /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:04:11.899+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/nasa_dag.py for tasks to queue
[2025-01-21T01:04:11.901+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:04:11.901+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:04:11.919+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:04:11.916+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/nasa_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nasa_dag.py", line 7, in <module>
    from airflow.providers.mongo.hooks.mongo import MongoHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2025-01-21T01:04:11.920+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:04:11.936+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/nasa_dag.py took 0.043 seconds
[2025-01-21T01:04:42.313+0000] {processor.py:186} INFO - Started process (PID=78) to work on /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:04:42.314+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/nasa_dag.py for tasks to queue
[2025-01-21T01:04:42.315+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:04:42.315+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:04:42.334+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:04:42.324+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/nasa_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nasa_dag.py", line 7, in <module>
    from airflow.providers.mongo.hooks.mongo import MongoHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2025-01-21T01:04:42.336+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:04:42.354+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/nasa_dag.py took 0.044 seconds
[2025-01-21T01:05:12.705+0000] {processor.py:186} INFO - Started process (PID=85) to work on /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:05:12.706+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/nasa_dag.py for tasks to queue
[2025-01-21T01:05:12.709+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:05:12.708+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:05:12.723+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:05:12.718+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/nasa_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nasa_dag.py", line 7, in <module>
    from airflow.providers.mongo.hooks.mongo import MongoHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2025-01-21T01:05:12.725+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:05:12.741+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/nasa_dag.py took 0.041 seconds
[2025-01-21T01:05:43.116+0000] {processor.py:186} INFO - Started process (PID=92) to work on /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:05:43.116+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/nasa_dag.py for tasks to queue
[2025-01-21T01:05:43.118+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:05:43.118+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:05:43.132+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:05:43.128+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/nasa_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nasa_dag.py", line 7, in <module>
    from airflow.providers.mongo.hooks.mongo import MongoHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2025-01-21T01:05:43.134+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:05:43.151+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/nasa_dag.py took 0.038 seconds
[2025-01-21T01:06:13.480+0000] {processor.py:186} INFO - Started process (PID=99) to work on /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:06:13.481+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/nasa_dag.py for tasks to queue
[2025-01-21T01:06:13.483+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:06:13.483+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:06:13.499+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:06:13.495+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/nasa_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nasa_dag.py", line 7, in <module>
    from airflow.providers.mongo.hooks.mongo import MongoHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2025-01-21T01:06:13.501+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:06:13.514+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/nasa_dag.py took 0.038 seconds
[2025-01-21T01:06:43.819+0000] {processor.py:186} INFO - Started process (PID=106) to work on /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:06:43.820+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/nasa_dag.py for tasks to queue
[2025-01-21T01:06:43.822+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:06:43.821+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:06:43.836+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:06:43.833+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/nasa_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nasa_dag.py", line 7, in <module>
    from airflow.providers.mongo.hooks.mongo import MongoHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2025-01-21T01:06:43.837+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:06:43.855+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/nasa_dag.py took 0.040 seconds
[2025-01-21T01:07:14.169+0000] {processor.py:186} INFO - Started process (PID=119) to work on /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:07:14.171+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/nasa_dag.py for tasks to queue
[2025-01-21T01:07:14.173+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:07:14.173+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:07:14.195+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:07:14.191+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/nasa_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nasa_dag.py", line 7, in <module>
    from airflow.providers.mongo.hooks.mongo import MongoHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2025-01-21T01:07:14.196+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:07:14.319+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/nasa_dag.py took 0.155 seconds
[2025-01-21T01:07:44.601+0000] {processor.py:186} INFO - Started process (PID=126) to work on /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:07:44.602+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/nasa_dag.py for tasks to queue
[2025-01-21T01:07:44.603+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:07:44.603+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:07:44.620+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:07:44.617+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/nasa_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nasa_dag.py", line 7, in <module>
    from airflow.providers.mongo.hooks.mongo import MongoHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2025-01-21T01:07:44.620+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:07:44.635+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/nasa_dag.py took 0.037 seconds
[2025-01-21T01:08:14.979+0000] {processor.py:186} INFO - Started process (PID=133) to work on /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:08:14.980+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/nasa_dag.py for tasks to queue
[2025-01-21T01:08:14.983+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:08:14.983+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:08:14.993+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:08:14.991+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/nasa_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nasa_dag.py", line 7, in <module>
    from airflow.providers.mongo.hooks.mongo import MongoHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2025-01-21T01:08:14.994+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:08:15.009+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/nasa_dag.py took 0.034 seconds
[2025-01-21T01:08:45.407+0000] {processor.py:186} INFO - Started process (PID=140) to work on /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:08:45.408+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/nasa_dag.py for tasks to queue
[2025-01-21T01:08:45.410+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:08:45.409+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:08:45.423+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:08:45.420+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/nasa_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nasa_dag.py", line 7, in <module>
    from airflow.providers.mongo.hooks.mongo import MongoHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2025-01-21T01:08:45.425+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:08:45.438+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/nasa_dag.py took 0.034 seconds
[2025-01-21T01:09:15.827+0000] {processor.py:186} INFO - Started process (PID=147) to work on /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:09:15.828+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/nasa_dag.py for tasks to queue
[2025-01-21T01:09:15.830+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:09:15.830+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:09:15.849+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:09:15.846+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/nasa_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nasa_dag.py", line 7, in <module>
    from airflow.providers.mongo.hooks.mongo import MongoHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2025-01-21T01:09:15.850+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:09:15.866+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/nasa_dag.py took 0.045 seconds
[2025-01-21T01:09:46.223+0000] {processor.py:186} INFO - Started process (PID=154) to work on /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:09:46.224+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/nasa_dag.py for tasks to queue
[2025-01-21T01:09:46.226+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:09:46.225+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:09:46.240+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:09:46.235+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/nasa_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nasa_dag.py", line 7, in <module>
    from airflow.providers.mongo.hooks.mongo import MongoHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2025-01-21T01:09:46.241+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:09:46.256+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/nasa_dag.py took 0.037 seconds
[2025-01-21T01:10:16.635+0000] {processor.py:186} INFO - Started process (PID=161) to work on /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:10:16.637+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/nasa_dag.py for tasks to queue
[2025-01-21T01:10:16.639+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:10:16.638+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:10:16.650+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:10:16.647+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/nasa_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nasa_dag.py", line 7, in <module>
    from airflow.providers.mongo.hooks.mongo import MongoHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2025-01-21T01:10:16.651+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:10:16.666+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/nasa_dag.py took 0.037 seconds
[2025-01-21T01:10:46.951+0000] {processor.py:186} INFO - Started process (PID=168) to work on /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:10:46.952+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/nasa_dag.py for tasks to queue
[2025-01-21T01:10:46.953+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:10:46.953+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:10:46.968+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:10:46.966+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/nasa_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nasa_dag.py", line 7, in <module>
    from airflow.providers.mongo.hooks.mongo import MongoHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2025-01-21T01:10:46.969+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:10:46.982+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/nasa_dag.py took 0.035 seconds
[2025-01-21T01:11:17.320+0000] {processor.py:186} INFO - Started process (PID=175) to work on /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:11:17.321+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/nasa_dag.py for tasks to queue
[2025-01-21T01:11:17.323+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:11:17.322+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:11:17.339+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:11:17.334+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/nasa_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nasa_dag.py", line 7, in <module>
    from airflow.providers.mongo.hooks.mongo import MongoHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2025-01-21T01:11:17.341+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:11:17.354+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/nasa_dag.py took 0.037 seconds
[2025-01-21T01:11:47.675+0000] {processor.py:186} INFO - Started process (PID=182) to work on /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:11:47.676+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/nasa_dag.py for tasks to queue
[2025-01-21T01:11:47.678+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:11:47.678+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:11:47.699+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:11:47.697+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/nasa_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nasa_dag.py", line 7, in <module>
    from airflow.providers.mongo.hooks.mongo import MongoHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2025-01-21T01:11:47.700+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:11:47.714+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/nasa_dag.py took 0.043 seconds
[2025-01-21T01:12:18.045+0000] {processor.py:186} INFO - Started process (PID=189) to work on /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:12:18.046+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/nasa_dag.py for tasks to queue
[2025-01-21T01:12:18.049+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:12:18.048+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:12:18.062+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:12:18.060+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/nasa_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nasa_dag.py", line 7, in <module>
    from airflow.providers.mongo.hooks.mongo import MongoHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2025-01-21T01:12:18.063+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:12:18.080+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/nasa_dag.py took 0.040 seconds
[2025-01-21T01:21:41.894+0000] {processor.py:186} INFO - Started process (PID=56) to work on /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:21:41.896+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/nasa_dag.py for tasks to queue
[2025-01-21T01:21:41.899+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:21:41.899+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:21:41.915+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:21:41.911+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/nasa_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nasa_dag.py", line 7, in <module>
    from airflow.providers.mongo.hooks.mongo import MongoHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2025-01-21T01:21:41.916+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:21:41.934+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/nasa_dag.py took 0.045 seconds
[2025-01-21T01:22:12.199+0000] {processor.py:186} INFO - Started process (PID=63) to work on /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:22:12.200+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/nasa_dag.py for tasks to queue
[2025-01-21T01:22:12.202+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:22:12.201+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:22:12.216+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:22:12.214+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/nasa_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nasa_dag.py", line 7, in <module>
    from airflow.providers.mongo.hooks.mongo import MongoHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2025-01-21T01:22:12.217+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:22:12.235+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/nasa_dag.py took 0.041 seconds
[2025-01-21T01:22:42.558+0000] {processor.py:186} INFO - Started process (PID=70) to work on /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:22:42.560+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/nasa_dag.py for tasks to queue
[2025-01-21T01:22:42.563+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:22:42.562+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:22:42.577+0000] {logging_mixin.py:190} INFO - [2025-01-21T01:22:42.574+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/nasa_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/nasa_dag.py", line 7, in <module>
    from airflow.providers.mongo.hooks.mongo import MongoHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2025-01-21T01:22:42.578+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/nasa_dag.py
[2025-01-21T01:22:42.600+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/nasa_dag.py took 0.047 seconds
